### ISSUE TITLE
Shantae and the Pirate's Curse help files .anb , .image and .font!

### ISSUE THREAD

**Issue by brtraducoes** [Lorenzooone/ShantaeText#2]
I'm looking to translate the game into Portuguese, but I'm having trouble extracting and editing the .anb, .image and .font files!
Can you help me?

**Comment by Lorenzooone** [comment]
Hello,
I have no idea what these extensions are, however if you're looking for the graphics and font, you can find a software that extracts and inserts them here: https://github.com/Lorenzooone/WayForwardComp .
They'll be extracted as .bin files, which can be opened with a tile editor like YY-CHR https://www.romhacking.net/utilities/119/ .

**Comment by Lorenzooone** [comment]
These tools are for the Game Boy Shantae game.
Not for Pirate's Curse.
You should look elsewhere for that.
